<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_tanggal_lahir</name>
   <tag></tag>
   <elementGuidId>34a03980-44b5-49bc-a6ef-eb4edd792a57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@name = 'tanggal_lahir']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;tanggal_lahir&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;tanggal_lahir&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b4f1d7fb-b18d-4f06-b936-f580f8468b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>58436bf5-cca8-4b03-84bd-3affb8612bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tanggal_lahir</value>
      <webElementGuid>9f56c39a-0e35-4804-945d-7cd9641d6e03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full bg-gray-50 rounded-xl border-none p-4 focus:ring-2 focus:ring-blue-500 outline-none</value>
      <webElementGuid>1fac754d-b90a-47e7-ab7e-0f3cceb77d71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-6c753f96afa9d4cc4c8a039f05cb26c5</value>
      <webElementGuid>791f332f-d9b3-4b3c-950e-9ce456255781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'tanggal_lahir']</value>
      <webElementGuid>501da8b9-1fa7-4e8e-a8cc-13276c29615c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'tanggal_lahir']</value>
      <webElementGuid>f993b000-1dd7-408c-91ff-8c778e35dba2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @name = 'tanggal_lahir']</value>
      <webElementGuid>775f90b1-fd59-42aa-ac03-932c2a2118c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
