<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Harga</name>
   <tag></tag>
   <elementGuidId>7990fc25-d3e2-47ef-b349-aa0e32261179</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@name = 'tindakan_harga[]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;tindakan_harga\[\]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Harga&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>586fcf6c-0977-4d76-9b6a-c3d78e7494ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>390cb557-d882-4cd9-93ff-f7a33298c613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tindakan_harga[]</value>
      <webElementGuid>9ff829fa-182e-4a42-9b71-203c03f8ea8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Harga</value>
      <webElementGuid>eec65eb5-8f28-4fcf-a079-70b428e5220a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>harga-input w-full bg-gray-50 p-3 rounded-lg border-none outline-none focus:ring-2 focus:ring-blue-500 text-sm</value>
      <webElementGuid>a44aff9c-68ec-4a3f-85fd-920f22515ff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>hitungTotal()</value>
      <webElementGuid>22c410c6-5e27-453b-9926-6eedfe1ca092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e319b5825d86b99d40c0c531fa476df7</value>
      <webElementGuid>89415d35-f8f4-4525-9ec3-e4f84b8b1bb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'tindakan_harga[]']</value>
      <webElementGuid>5e58e181-239c-4ff9-bbdf-9a392cef20dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'tindakan_harga[]']</value>
      <webElementGuid>68b96e57-0ee5-4a13-9d3e-489a809b2a68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'tindakan_harga[]' and @placeholder = 'Harga']</value>
      <webElementGuid>78952db7-4491-4a3f-987a-13009f4ea322</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
