<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Harga</name>
   <tag></tag>
   <elementGuidId>6e2267cc-7633-4f98-bc4d-315d74ccd32d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'number' and @name = 'tindakan_harga[]' and @placeholder = 'Harga']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@name = 'tindakan_harga[]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;tindakan_harga\[\]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Harga&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>13265ed3-6fd7-44a2-9928-90af82458a25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>0d31c1db-0c19-444c-b758-a35af37b6e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tindakan_harga[]</value>
      <webElementGuid>180e5295-aa76-4aa5-861d-2a0a5748cee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Harga</value>
      <webElementGuid>4dbc2fbe-07aa-42e1-aa6a-385290604249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>harga-input w-full bg-gray-50 p-3 rounded-lg border-none outline-none focus:ring-2 focus:ring-blue-500 text-sm</value>
      <webElementGuid>89fda075-cfa1-486f-a1ae-dd5e49761e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>hitungTotal()</value>
      <webElementGuid>22bef25a-0b01-48c6-804c-d76eabd2e027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e319b5825d86b99d40c0c531fa476df7</value>
      <webElementGuid>baef79af-bb76-4117-b3d7-a58213e84ac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'tindakan_harga[]']</value>
      <webElementGuid>64b14eff-3a08-4eda-b5ac-c507133ee7ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'tindakan_harga[]']</value>
      <webElementGuid>a4833678-5052-49ed-b2c1-154a89491d83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'tindakan_harga[]' and @placeholder = 'Harga']</value>
      <webElementGuid>2a93f45f-80b5-4253-acd4-73761efc84d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
