<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_tgl_akhir</name>
   <tag></tag>
   <elementGuidId>39539eb1-a144-4dd6-86e1-29ecadb3df48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@name = 'tgl_akhir']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;tgl_akhir&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;tgl_akhir&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4182792e-d5a4-4850-bdd4-28990e6e2708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>3ca587b0-dff0-48b4-a6e2-8eea4c3d41b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tgl_akhir</value>
      <webElementGuid>b9946a7b-529e-49f7-a1ca-d5f18183ddae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2026-04-30</value>
      <webElementGuid>1bbe822f-5c11-48e3-b44c-c1c08e1396a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-gray-50 p-3 rounded-lg outline-none</value>
      <webElementGuid>572b303f-3b7e-4f11-8d38-30a8fd6a28ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-daee9da33f404d64dccc54dbefd352a3</value>
      <webElementGuid>be3ae670-636c-41d0-a78b-2ae0eec9640b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'tgl_akhir']</value>
      <webElementGuid>52190a1b-896c-450a-b33b-7f0cfbffdf3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'tgl_akhir']</value>
      <webElementGuid>133c7ab8-2036-4d02-8275-eaa28b235b4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @name = 'tgl_akhir']</value>
      <webElementGuid>b1ad31a9-ad2f-4c3c-8e06-18c1ecf71f4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
