<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_tgl_awal</name>
   <tag></tag>
   <elementGuidId>93d6be76-466e-49e1-be0c-8bcc51b132d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@name = 'tgl_awal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;tgl_awal&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;tgl_awal&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>10354cb1-8b6b-4f4e-80ed-3c363fdcf594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>76d1ac2e-a469-4c42-b896-73b1046ce011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tgl_awal</value>
      <webElementGuid>ba8e7072-f89e-4ae5-bcdf-4a614ac58265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2026-04-30</value>
      <webElementGuid>743042b8-5f65-4d54-b3ed-5608b6203877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-gray-50 p-3 rounded-lg outline-none</value>
      <webElementGuid>60296bc9-9911-4003-a3a2-49ea1b151d2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-b0af90ef5eb14c6eac93d83d6b7cbdae</value>
      <webElementGuid>dd26cf81-8682-4f75-9404-bbf3a975315f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'tgl_awal']</value>
      <webElementGuid>48a5380a-7c5b-4fbc-848c-1e911ebfd4cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'tgl_awal']</value>
      <webElementGuid>9206ac0f-5f7a-4b32-a57c-ffd15eb85691</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @name = 'tgl_awal']</value>
      <webElementGuid>889b5348-519b-4203-8123-69bc7aba275e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
