<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Konfirmasi Pembayaran  Cetak Struk</name>
   <tag></tag>
   <elementGuidId>6bdad4ff-8cdb-494f-9496-a765d1c6f374</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit' and contains(normalize-space(.), 'Konfirmasi Pembayaran')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[type="submit"].bg-purple-600</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>31754244-8a66-454c-8473-efe6364e6453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>1ea4dc0a-5905-45e3-b289-2c4e910a9f67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit' and contains(normalize-space(.), 'Konfirmasi Pembayaran')]</value>
      <webElementGuid>9f76157f-c04b-47d1-a4d3-fc5ace4d1eb6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
