<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Total Biaya</name>
   <tag></tag>
   <elementGuidId>703ff393-462e-41b4-833a-2601bfa68795</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name="total_biaya"]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name="total_biaya"]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f3de59fb-5954-43ec-84e0-d64f0410feb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name="total_biaya"]</value>
      <webElementGuid>18565a4b-1f04-4dc5-9059-1e49fb4db817</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
