<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Badge Counter</name>
   <tag></tag>
   <elementGuidId>b0f10781-4e44-4464-aece-43668b6ae6be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id="badge-count"]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#badge-count</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e90d761f-0421-4782-86a2-123cbceacad4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id="badge-count"]</value>
      <webElementGuid>7e475fc4-4186-4c54-86ab-cdd26d46369e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
